add folder path to project

In [1]:
import os,sys

In [2]:
dirname = os.path.abspath('')
print(dirname)
dirname = "/".join(dirname.split("/")[:-1])
print(dirname)
sys.path.append(dirname)


/Users/yoavkitai/Documents/Bynet/repositories/http_proj/unitTest
/Users/yoavkitai/Documents/Bynet/repositories/http_proj


imports

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from MinMaxScale import MinMaxScale
from kneighbors import KnnClassifier
from knn_brute import KNNBrute
from keras.datasets import mnist
import cv2
from imgConv import getImageAsArray
import pickle

(X_tr, y_train), (X_te, y_test) = mnist.load_data()
y_train = np.array(y_train).T
y_test = np.array(y_test).T
X_train = []
X_test = []

# image_array = []
# for i in range(1,10):
#     f = 
#     file_bytes = np.frombuffer(f, np.uint8)
#     image_array.append(getImageAsArray(f'./imgTst/{i}.png'))
# image_array = np.array(image_array)
# print(image_array.shape)

for img_xtr in X_tr:
    X_train.append(img_xtr.reshape(img_xtr.shape[0]*img_xtr.shape[1]))
for img_xte in X_te:
    X_test.append(img_xte.reshape(img_xte.shape[0]*img_xte.shape[1]))
X_train = np.array(X_train)
X_test = np.array(X_test)
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(60000, 784)
(60000,)
(10000, 784)
(10000,)


import data

In [4]:
data = pd.read_csv('titanic_data.csv')
data.drop(["Name", "Ticket", "PassengerId"], axis=1, inplace=True)
encoder = LabelEncoder()
data["Sex"] = encoder.fit_transform(data["Sex"])
encoder = LabelEncoder()
data["Cabin"] = encoder.fit_transform(data["Cabin"])
encoder = LabelEncoder()
data["Embarked"] = encoder.fit_transform(data["Embarked"])
data


Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Cabin  Embarked
0           0       3    1  22.0      1      0   7.2500    147         2
1           1       1    0  38.0      1      0  71.2833     81         0
2           1       3    0  26.0      0      0   7.9250    147         2
3           1       1    0  35.0      1      0  53.1000     55         2
4           0       3    1  35.0      0      0   8.0500    147         2
..        ...     ...  ...   ...    ...    ...      ...    ...       ...
886         0       2    1  27.0      0      0  13.0000    147         2
887         1       1    0  19.0      0      0  30.0000     30         2
888         0       3    0   NaN      1      2  23.4500    147         2
889         1       1    1  26.0      0      0  30.0000     60         0
890         0       3    1  32.0      0      0   7.7500    147         1

[891 rows x 9 columns]

In [5]:
data.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Cabin         0
Embarked      0
dtype: int64

In [6]:
data.dropna(inplace=True)

In [7]:
data

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Cabin  Embarked
0           0       3    1  22.0      1      0   7.2500    147         2
1           1       1    0  38.0      1      0  71.2833     81         0
2           1       3    0  26.0      0      0   7.9250    147         2
3           1       1    0  35.0      1      0  53.1000     55         2
4           0       3    1  35.0      0      0   8.0500    147         2
..        ...     ...  ...   ...    ...    ...      ...    ...       ...
885         0       3    0  39.0      0      5  29.1250    147         1
886         0       2    1  27.0      0      0  13.0000    147         2
887         1       1    0  19.0      0      0  30.0000     30         2
889         1       1    1  26.0      0      0  30.0000     60         0
890         0       3    1  32.0      0      0   7.7500    147         1

[714 rows x 9 columns]

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 714 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  714 non-null    int64  
 1   Pclass    714 non-null    int64  
 2   Sex       714 non-null    int64  
 3   Age       714 non-null    float64
 4   SibSp     714 non-null    int64  
 5   Parch     714 non-null    int64  
 6   Fare      714 non-null    float64
 7   Cabin     714 non-null    int64  
 8   Embarked  714 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 55.8 KB


In [9]:
# X = data.drop('Survived', axis=1)
# X = data.to_numpy()
# y = data['Survived']
# y = y.to_numpy()
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.40, random_state=42)

In [10]:
knn_model = KnnClassifier(k_neighbors = 7, depth=2)

In [11]:
knn_model.fit(X_train, y_train)

In [12]:
tree = knn_model.tree.tree
for i in range(1000):
    print(tree)
    if tree == None:
        break
    if tree.right_child == None:
        print("!!!!!!", i)
        print(tree.data_x)
    else:
        print(i)
    tree = tree.right_child

0
!!!!!! 1
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
None


In [13]:
y_pred = knn_model.predict(X_test)

In [14]:
print(y_pred)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [15]:
print(accuracy_score(y_test, y_pred))

0.1135


In [16]:
knn_brute = KNNBrute(k_neighbors=7)
knn_brute.fit(X_train, y_train)
# y_pred_brute = knn_brute.predict(X_test)
# y_pred_brute


In [17]:
# accuracy_score(y_test, y_pred_brute)

In [18]:
pickle_model = pickle.dumps(knn_brute)
print(pickle_model)

In [ ]:
from manDB import dataBase

mydb = dataBase()
mydb.export_model("brute knn", pickle_model)